routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\LibrarianBookController;
use App\Http\Controllers\ExtraditionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {

    // Users
    Route::middleware(['role:admin'])->group(function () {
        Route::resource('users', UserController::class);
        Route::get('users/change_password/{user}', [UserController::class, 'changePassword'])->name('change_password.form');
        Route::post('users/change_password', [UserController::class, 'changePasswordStore'])->name('change_password.store');
    });

    // Librarian Books
    Route::prefix('librarian')->middleware(['role:librarian,admin'])->name('librarian.')->group(function () {
        Route::resource('books', LibrarianBookController::class);
        Route::get('books/give_out/{book}', [LibrarianBookController::class, 'giveOut'])->name('give_out.form');
        Route::post('books/give_out', [LibrarianBookController::class, 'giveOutStore'])->name('give_out.store');
        Route::post('books/accept/{book}', [LibrarianBookController::class, 'acceptStore'])->name('accept.store');
    });

    // Books
    Route::middleware(['role:client,admin,librarian'])->group(function () {
        Route::resource('books', BookController::class);
        Route::post('books/reserve/{book}', [BookController::class, 'reserveBook'])->name('reserve_book.store');
        Route::post('books/cancel_reservation/{book}', [BookController::class, 'cancelReservation'])->name('cancel_reservation.store');
        Route::post('books/search', [BookController::class, 'booksSearch'])->name('books.search');

    });

});

require __DIR__ . '/auth.php';

app/Http/Controllers/LibrarianBookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\BookStatus;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class LibrarianBookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('bookStatus.user')->get()->sortByDesc('bookStatus.status');

        return view('librarian-books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('librarian-books._form-create_book');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'author' => 'required|string|max:255',
            'genre' => 'required|string|max:255',
            'publisher' => 'required|string|max:255',
        ]);

        $book = Book::create([
            'name' => $request->name,
            'author' => $request->author,
            'genre' => $request->genre,
            'publisher' => $request->publisher,
        ]);

        if ($book) {
            $bookStatus = new BookStatus(['status' => 1]);
            $book->bookStatus()->save($bookStatus);
        }

        if ($book) {
            return redirect()->route('librarian.books.index')->with('success','Book successfully created.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);

        if ($book) {
            $book->delete();

            return back()->with('success','Book successfully deleted.');
        }
    }

    public function giveOut($id)
    {
        $book = Book::findOrFail($id);

        return view('librarian-books._form-give_out', ['book' => $book]);
    }

    public function giveOutStore(Request $request)
    {
        $request->validate([
            'user_id' => 'required|integer|max:255',
            'book_id' => 'required|integer|max:255',
        ]);

        $userId = $request->user_id;
        $bookId = $request->book_id;

        $book = Book::with('bookStatus')->find($bookId);

        $updateBookStatus = $book->bookStatus()->update([
            'status' => 3,
            'user_id' => $userId,
            'book_id' => $bookId,
            'start_reservation' => $request->start_reservation,
            'end_reservation' => $request->end_reservation,
        ]);

        if ($updateBookStatus) {
            return back()->with('success','Book status successfully updated.');
        }
    }

    public function acceptStore($bookId)
    {
        $book = Book::with('bookStatus')->find($bookId);

        $updateBookStatus = $book->bookStatus()->update([
            'status' => 1,
            'user_id' => null,
            'book_id' => $bookId,
            'start_reservation' => null,
            'end_reservation' => null,
        ]);

        if ($updateBookStatus) {
            return back()->with('success','Book status successfully updated.');
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/librarian-books/_form-create_book.blade.php
@section('title','Create book')

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create book') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <form method="POST" action="{{ route('librarian.books.store') }}">

                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" id="name" required>
                        </div>

                        <div class="form-group">
                            <label for="author">Author</label>
                            <input type="text" class="form-control" name="author" id="author" required>
                        </div>

                        <div class="form-group">
                            <label for="genre">Genre</label>
                            <input type="text" class="form-control" name="genre" id="genre" required>
                        </div>

                        <div class="form-group">
                            <label for="publisher">Publisher</label>
                            <input type="text" class="form-control" name="publisher" id="publisher" required>
                        </div>

                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/librarian-books/_form-give_out.blade.php
@section('title','Give out book')

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Give out book') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <h2>{{ $book->name }}</h2>

                    <form method="POST" action="{{ route('librarian.give_out.store', $book->id) }}">

                        <input type="hidden" name="book_id" value="{{ $book->id }}">
                        <input type="hidden" name="user_id" value="{{ $book->bookStatus->user->id }}">

                        <div class="form-group row">
                            <label for="start_reservation" class="col-2 col-form-label">Start reservation</label>
                            <div class="col-10">
                                <input class="form-control" type="date" value="{{ date('Y-m-d') }}" name="start_reservation"
                                       id="start_reservation">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="end_reservation" class="col-2 col-form-label">End reservation</label>
                            <div class="col-10">
                                <input class="form-control" type="date" value="{{ date("Y-m-d", strtotime("+1 week")) }}" name="end_reservation"
                                       id="end_reservation">
                            </div>
                        </div>

                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/librarian-books/index.blade.php
@section('title','Librarian books')

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Librarian books') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <a href="{{ route('librarian.books.create') }}" class="btn btn-primary btn-sm mb-3">Create</a>

                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Author</th>
                            <th scope="col">Genre</th>
                            <th scope="col">Publisher</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created at</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($books as $key => $book)
                            <tr>
                                <th scope="row">{{ $book->id }}</th>
                                <td>{{ $book->name }}</td>
                                <td>{{ $book->author }}</td>
                                <td>{{ $book->genre }}</td>
                                <td>{{ $book->publisher }}</td>
                                <td>
                                    @if($book->bookStatus->status == 1)
                                        <span class="badge badge-success">Published</span>
                                    @elseif($book->bookStatus->status == 2)
                                        <span
                                            class="badge badge-danger">Reserved by {{ $book->bookStatus->user->name }}</span>
                                    @elseif($book->bookStatus->status == 3)
                                        <span
                                            class="badge badge-warning">Given to {{ $book->bookStatus->user->name }}</span>
                                    @endif
                                </td>
                                <td>{{ $book->created_at }}</td>
                                <td>
                                    @if($book->bookStatus->status == 2)
                                        <a href="{{ route('librarian.give_out.form', $book->id) }}"
                                           class="btn btn-primary btn-sm">Give out</a>
                                    @endif

                                    @if($book->bookStatus->status == 3)
                                        <form method="POST" action="{{ route('librarian.accept.store', $book->id) }}">
                                            {{ csrf_field() }}
                                            <input type="submit" class="btn btn-info btn-sm"
                                                   onclick="return confirm('Are you sure?')" value="Accept">
                                        </form>
                                    @endif
                                    <form method="POST" action="{{ route('librarian.books.destroy', $book->id) }}">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <input type="submit" class="btn btn-danger btn-sm"
                                               onclick="return confirm('Are you sure?')" value="Delete">
                                    </form>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>